spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&serverTimezone=UTC&characterEncoding=utf-8
        username: root
        password: root
        #      filters: stat,wall,log4j,config
        max-active: 100 #最大连接数
        initial-size: 1  #初始化大小
        max-wait: 60000
        min-idle: 1  #最小连接数
        time-between-eviction-runs-millis: 60000  #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000  #一个连接在池中最小生存的时间，单位是毫秒
        validation-query: select 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 50
        max-pool-prepared-statement-per-connection-size: 20
      db2:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@//192.168.1.15:1521/orcl
        username: ztapp
        password: ztapp
        #      filters: stat,wall,log4j,config
        max-active: 100 #最大连接数
        initial-size: 1  #初始化大小
        max-wait: 60000
        min-idle: 1  #最小连接数
        time-between-eviction-runs-millis: 60000  #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        min-evictable-idle-time-millis: 300000  #一个连接在池中最小生存的时间，单位是毫秒
        validation-query: SELECT * from dual
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-open-prepared-statements: 50
        max-pool-prepared-statement-per-connection-size: 20
  # mybaties
mybatis:
  mapper-locations: classpath:mapper/admin/*.xml
